file = open("myfile.txt","w")
file.write("This is the write command")
file.write("This allows us to write in a particular file")
file = open("myfile.txt","r")
print(file.read())
file = open("myfile.txt","r")
print.write("This will add this line")
file = open("myfile.txt","r")
print(file.read())
print(file.readline(8))
file.seek(0)
print(file.readlines())
file = open("myfile.txt","w")
w = "Hello"
l = ["\nThis is first line\n","This is second line\n","This is third line\n"]
file.write(w)
file.writelines(l)
file = open("myfile.txt","r")
print(file.read())
print(file.readline(8))
file.seek(0)
print(file.readlines())
file.close()