from tkinter import *
root=Tk()
Label (root, text = "ITVoyagers Registration Form", bg="blue", fg="white",font="Verdana 16 bold italic").grid(row=0, columnspan=5)
lab= Label( root, text= "Name of visitor", height=2, width=15,fg='blue',font="BOLD")
lab.grid(row=1,column=1,sticky=W)
w=Entry(root)
w.grid(row=1,column=2)
lab= Label( root, text= "Favourite programming language", height=2, width=25,fg='blue',font="BOLD")
lab.grid(row=2,column=1,sticky=W)
w=Entry(root)
w.grid(row=2,column=2)
lab= Label( root, text= "Gender", height=2, width=15,fg='blue',font="BOLD")
lab.grid(row=3,column=1,sticky=W)
var=IntVar()
w=Radiobutton(root, text= "Male",variable= var, value=1)
w.grid(row=3,column=2,sticky=N)
w=Radiobutton(root, text= "Female",variable= var, value=2)
w.grid(row=4,column=2,sticky=N)

lab= Label( root, text= "Address", height=2, width=15,fg='blue',font="BOLD")
lab.grid(row=5,column=1,sticky=W)
w=Text( root, bd=2,height=5,width=15,relief=RAISED )
w.insert(INSERT,"Edit here")
w.grid(row=5,column=2)

lab= Label( root, text= "Email id", height=2, width=15,fg='blue',font="BOLD")
lab.grid(row=6,column=1,sticky=W)
w=Entry(root)
w.grid(row=6,column=2)

lab= Label( root, text= "Contact no", height=2, width=15,fg='blue',font="BOLD")
lab.grid(row=7,column=1,sticky=W)
w=Entry(root)
w.grid(row=7,column=2)

lab= Label( root, text= "Country", height=2, width=15,fg='blue',font="BOLD")
lab.grid(row=8,column=1,sticky=W)
w=Entry(root)
w.grid(row=8,column=2)

lab= Label( root, text= "State", height=2, width=15,fg='blue',font="BOLD")
lab.grid(row=9,column=1,sticky=W)
w=Entry(root)
w.grid(row=9,column=2)

CheckVar1=IntVar()
CheckVar2=IntVar()
Label(root,text="Select topics you wish to learn",fg='blue',font="BOLD").grid(row=10,column=1,sticky=W)
C1=Checkbutton(root,text="Python",variable=CheckVar1)
C2=Checkbutton(root,text="Business Intelligence",variable=CheckVar2)
C1.grid(row=10,column=2,sticky=N)
C2.grid(row=11,column=2,sticky=N)

B=Button(root,text="REGISTER HERE", height=1, width=15, bg="blue", fg="White",font="Verdana 16 bold")
B.grid(row=12,columnspan=3)
